Add sub-template form
plone/bobtemplates.plone pull request #523
Opened 2022-10-20 14:18 UTC by MrTango

2022-10-21 09:07 UTC, mamico commented on skeleton-tests/test_addon_all.py
> +view_register_for=Folder
@MrTango to make tests working, you need to add `subtemplate_warning=True` in answers' template here, or to commit changes. (this is the mrbob's question  you are missing to reply 'Please commit your changes, before using a sub-template! Continue anyway? [N/y]').

2022-10-21 21:08 UTC, mamico requested changes

2022-10-21 21:08 UTC, mamico commented on package_tests/test_form.py
> +            "form_python_class_name": "MyForm",
```suggestion
        target_directory=target_path,
        bobconfig={"non_interactive": True},
        variables={
            "form_python_file_name": "py_form",
            "form_python_class_name": "MyForm",
```

IMO `target_directory` needs to be an absolute path (or change current working directory to `tmpdir`), and `form_python_file_name` in configurator is required if not managed by `prepare_renderer`

2022-10-24 06:28 UTC, MrTango commented
thx @mamico i was hunting in the wrong direction i guess ;)

2022-10-24 06:55 UTC, merged